AllPermissions:
  Effect: Allow
  Action:
    - dynamodb:GetItem
    - dynamodb:Query
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DescribeTable
  Resource:
    - !GetAtt ApplicationTable.Arn
    - !Join [ '', [ !GetAtt ApplicationTable.Arn, "/*" ] ]